server:
  port: 8010

spring:
  application:
    name: spirng-bobo
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
  jms:       #只设为true，topic类型生效，无法发送和接收queue消息
    pub-sub-domain: true
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root

# 如果想看到mybatis日志需要做如下配置
logging:
  level:
    com:
      battcn: DEBUG

########## Mybatis 自身配置 ##########
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hytx.bobo.model
# 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  configuration:
    map-underscore-to-camel-case: true
########## 通用Mapper ##########
# 主键自增回写方法,默认值MYSQL,详细说明请看文档
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
# 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
# 枚举按简单类型处理
  enum-as-simple-type: true

########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true


#eureka.client.serviceUrl.defaultZone=http://localhost:8000/eureka/
